[sw] Link to libgcc for run-time built-ins, required with -O0.
Without this, compiling with -O0 results in: undefined reference to `__udivdi3'

  usec_cycles = CLK_FIXED_FREQ_HZ * usec / 1000 / 1000 / 8;

These built-ins are provided by libgcc. Add libgcc to LIBS as -lgcc.

Signed-off-by: Leon Woestenberg <leon@sidebranch.com>